
language: python
python:
- '3.8'
cache: false

install:
- python -V
- pip install -U virtualenv
- virtualenv venv
- source venv/bin/activate
- pip install -U flit
- pip install -U pytest
- pip install -U mypy
- pip install -U yaqc
- pip install -U yaqd-core
- pip install -U yaq-traits
- pip install .

jobs:
   include:
   - stage: test
     name: mypy
     script: mypy yaqd_wright
   - stage: test
     name: entry-points
     script:
            - yaqd-wright-wl-motor --version
            - yaqd-wright-wl-motor -h
            - yaqd-wright-filter-wheel --version
            - yaqd-wright-filter-wheel -h
            - yaqd-wright-aerotech --version
            - yaqd-wright-aerotech -h
            - yaqd-wright-ingaas --version
            - yaqd-wright-ingaas -h
   - stage: test
     name: traits
     script: for i in yaqd_wright/*.avpr; do yaq-traits check $i; done


deploy:
  provider: script
  script: flit publish
  on:
    tags: true

# Need to add env vars for FLIT_USERNAME and FLIT_PASSWORD once initial release is out
